<a href="https://colab.research.google.com/github/Irfanayousef/ML-LAB/blob/main/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:

a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
a=np.arange(20).reshape(2,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [4]:
print(a.shape)

(2, 10)


In [7]:
a=np.array([[1,2],[3,4]])
print(a)


[[1 2]
 [3 4]]


In [8]:
a=np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0]=5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [9]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

[[1 2 3]
 [4 5 6]]
(2, 3)
1 2 4
